// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgbsymavpwkqzaesfamx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnYnN5bWF2cHdrcXphZXNmYW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODY2MzUsImV4cCI6MjA1OTU2MjYzNX0.Gx87WeUmSkAiJUBt6mFv-RM9biftshgb37DHDGDDRu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);